#version: "3.9" # docker version --> 버전2이상 부터는 굳이 명시 안해줘도 된다고 함.

services:
  # DB
  mysql:
    container_name: mysql
    build: ./mysql
    ports:
      - "3306:3306"
    networks:
      - app-tier
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql-data:/var/lib/mysql

  # was
  django_app:
    container_name: django_app
    build:
      context: .
      dockerfile: ./django/Dockerfile
    command:
      bash -c "
      chmod +x ./wait-for-it.sh &&
      ./wait-for-it.sh mysql:3306 -t 10 &&
      python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      gunicorn admin.wsgi:application --bind 0.0.0.0:8000"
    ports:  # 외부 노출
      - "8000:8000"
    expose:  # 컨테이너의 포트를 다른 컨테이너에게만 공개
      - "8000"
    depends_on:
      - mysql
    links:
      - mysql:mysql
    restart: always # 변경사항 있을 때마다 리스타트
    volumes:
      - ./django:/app
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge

volumes:
  mysql-data:
